services:
  - type: web
    name: restaurante-api
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/restaurante-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 10000
      - key: SPRING_PROFILES_ACTIVE
        value: production
